services:
  - type: web
    name: ecoroute-api
    runtime: python
    region: singapore
    plan: starter
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    healthCheckPath: /health
    envVars:
      - key: NEO4J_URI
        value: neo4j+s://96f11763.databases.neo4j.io
      - key: NEO4J_USER
        value: 96f11763
      - key: NEO4J_DATABASE
        value: 96f11763
      - key: NEO4J_PASSWORD
        sync: false
      - key: CPCB_API_KEY
        value: 579b464db66ec23bdd00000129ca663565f3487e68329466cdd8da2c
      - key: TAVILY_API_KEY
        value: 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
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: CORS_ORIGINS
        value: "http://localhost:5173,https://ecoroute.vercel.app"
